### ISSUE TITLE
icloud hängt email-Properties an ics-Dateien an => ical4j hasst die

### ISSUE THREAD

**Issue by christf** [christf/SnuselPi#1]
/home/christof/.calendars/christof/iCal-20151225-153744.ics
Exception in thread "main" net.fortuna.ical4j.data.ParserException: Error at line 9:Unsupported parameter name: EMAIL
    at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:143)
    at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
    at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
    at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:165)
    at com.penguineering.snuselpi.Weckzeitfinder.main(Weckzeitfinder.java:50)
Caused by: java.lang.IllegalArgumentException: Unsupported parameter name: EMAIL
    at net.fortuna.ical4j.model.ParameterFactoryImpl.createParameter(ParameterFactoryImpl.java:90)
    at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.parameter(CalendarBuilder.java:273)
    at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(CalendarParserImpl.java:328)
    at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.access$1700(CalendarParserImpl.java:283)
    at net.fortuna.ical4j.data.CalendarParserImpl$ParameterListParser.parse(CalendarParserImpl.java:271)
    at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:208)
    at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:190)
    at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:173)
    at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:383)
    at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:367)
    at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:171)
    at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:122)
    ... 4 more

**Comment by christf** [comment]
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
VERSION:2.0
PRODID:-//CALENDARSERVER.ORG//NONSGML Version 1//EN
METHOD:REQUEST
BEGIN:VEVENT
ATTENDEE;CN=XXXXXX XXXXXXX;CUTYPE=INDIVIDUAL;RSVP=TRUE:mailto:
 xxxxxxxxxx@gmx.net
ATTENDEE;CUTYPE=INDIVIDUAL;EMAIL=xxxxxxxxxxxxxxxxx@icloud.com;
 PARTSTAT=ACCEPTED;CN=XXXXX XXXXX XXXXXXX:mailto:
 XXXXXXXXXXXXX@XXXXXXXXXXXX.de
ATTENDEE;CN=Herr xxxxxxxxx xxxxxxxxxx;CUTYPE=INDIVIDUAL;RSVP=TRUE:mailto:
 XXXXXXXXXXXXXXXX@gmx.net
CREATED:20151225T233447Z
DTEND;VALUE=DATE:20160425
DTSTART;VALUE=DATE:20160422
LAST-MODIFIED:20151225T233741Z
LOCATION:XXXXXX
RRULE:FREQ=WEEKLY;UNTIL=20160422
SEQUENCE:0
SUMMARY:XXXXXXXXXXXXXXXXXX
TRANSP:OPAQUE
UID:C8F2054E-ED58-482D-831A-611495F7F653
DTSTAMP:20151225T233744Z
ORGANIZER;CN=XXXXX XXXXX XXXXXXX;EMAIL=XXXXXXXXXXXXX@XXXXXXXXXXXX.de:
 mailto:
 2_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXX@imip.me.com
END:VEVENT
END:VCALENDAR

**Comment by christf** [comment]
Workaround: Icloud nicht benutzen, es müsste X-EMAIL heißen.
